//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.225
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCFChat
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ConsoleClient.IMessageKeeper")]
    public interface IMessageKeeper
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageKeeper/GetNewMessages", ReplyAction="http://tempuri.org/IMessageKeeper/GetNewMessagesResponse")]
        string GetNewMessages(int userid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageKeeper/SendMessage", ReplyAction="http://tempuri.org/IMessageKeeper/SendMessageResponse")]
        void SendMessage(int userid, string message);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMessageKeeper/LogIn", ReplyAction="http://tempuri.org/IMessageKeeper/LogInResponse")]
        int LogIn(string nickname);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMessageKeeperChannel : WCFChat.IMessageKeeper, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MessageKeeperClient : System.ServiceModel.ClientBase<WCFChat.IMessageKeeper>, WCFChat.IMessageKeeper
    {
        
        public MessageKeeperClient()
        {
        }
        
        public MessageKeeperClient(string endpointConfigurationName) : 
                base(endpointConfigurationName)
        {
        }
        
        public MessageKeeperClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MessageKeeperClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress)
        {
        }
        
        public MessageKeeperClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public string GetNewMessages(int userid)
        {
            return base.Channel.GetNewMessages(userid);
        }
        
        public void SendMessage(int userid, string message)
        {
            base.Channel.SendMessage(userid, message);
        }
        
        public int LogIn(string nickname)
        {
            return base.Channel.LogIn(nickname);
        }
    }
}
