[assembly: System.Reflection.AssemblyVersion("1.2.0.0")]
[assembly: System.Reflection.AssemblyFileVersion("1.2.311.0")]
[assembly: System.Reflection.AssemblyCopyright("(c) WarSpot team.")]
[assembly: System.Reflection.AssemblyProduct("WarSpot")]
[assembly: System.Reflection.AssemblyCompany("WarSpot team")]
[assembly: System.Reflection.AssemblyDefaultAlias("WarSpot.XNA.Lite.dll")]
[assembly: System.Reflection.AssemblyTitle("WarSpot.XNA.Lite.dll")]
[assembly: System.Reflection.AssemblyDescription("WarSpot.XNA.Lite.dll")]
[assembly: System.CLSCompliant(true)]
